using Domain_Layer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace InfrastructureLayer.Helpers
{
	public static class ModelBuilderExtensions
	{
		public static void SeedRoles( this ModelBuilder builder )
		{
			builder.Entity<IdentityRole>().HasData(
				new IdentityRole { Id = Guid.NewGuid().ToString(), Name = "Admin", NormalizedName = "Admin".ToUpper() },
				new IdentityRole { Id = Guid.NewGuid().ToString(), Name = "Customer", NormalizedName = "Customer".ToUpper() },
				new IdentityRole { Id = Guid.NewGuid().ToString(), Name = "Vendor", NormalizedName = "Vendor".ToUpper() },
				new IdentityRole { Id = Guid.NewGuid().ToString(), Name = "ServiceProvider", NormalizedName = "ServiceProvider".ToUpper() }
			);
		}

		public static void SeedGovernorate( this ModelBuilder builder )
		{
			builder.Entity<Governorate>().HasData(
				new Governorate { ID = 1, NameAr = "القاهرة", NameEn = "Cairo" },
				new Governorate { ID = 2, NameAr = "الجيزة", NameEn = "Giza" },
				new Governorate { ID = 3, NameAr = "الأسكندرية", NameEn = "Alexandria" },
				new Governorate { ID = 4, NameAr = "الدقهلية", NameEn = "Dakahlia" },
				new Governorate { ID = 5, NameAr = "البحر الأحمر", NameEn = "Red Sea" },
				new Governorate { ID = 6, NameAr = "البحيرة", NameEn = "Beheira" },
				new Governorate { ID = 7, NameAr = "الفيوم", NameEn = "Fayoum" },
				new Governorate { ID = 8, NameAr = "الغربية", NameEn = "Gharbiya" },
				new Governorate { ID = 9, NameAr = "الإسماعلية", NameEn = "Ismailia" },
				new Governorate { ID = 10, NameAr = "المنوفية", NameEn = "Menofia" },
				new Governorate { ID = 11, NameAr = "المنيا", NameEn = "Minya" },
				new Governorate { ID = 12, NameAr = "القليوبية", NameEn = "Qaliubiya" },
				new Governorate { ID = 13, NameAr = "الوادي الجديد", NameEn = "New Valley" },
				new Governorate { ID = 14, NameAr = "السويس", NameEn = "Suez" },
				new Governorate { ID = 15, NameAr = "اسوان", NameEn = "Aswan" },
				new Governorate { ID = 16, NameAr = "اسيوط", NameEn = "Assiut" },
				new Governorate { ID = 17, NameAr = "بني سويف", NameEn = "Beni Suef" },
				new Governorate { ID = 18, NameAr = "بورسعيد", NameEn = "Port Said" },
				new Governorate { ID = 19, NameAr = "دمياط", NameEn = "Damietta" },
				new Governorate { ID = 20, NameAr = "الشرقية", NameEn = "Sharkia" },
				new Governorate { ID = 21, NameAr = "جنوب سيناء", NameEn = "South Sinai" },
				new Governorate { ID = 22, NameAr = "كفر الشيخ", NameEn = "Kafr Al sheikh" },
				new Governorate { ID = 23, NameAr = "مطروح", NameEn = "Matrouh" },
				new Governorate { ID = 24, NameAr = "الأقصر", NameEn = "Luxor" },
				new Governorate { ID = 25, NameAr = "قنا", NameEn = "Qena" },
				new Governorate { ID = 26, NameAr = "شمال سيناء", NameEn = "North Sinai" },
				new Governorate { ID = 27, NameAr = "سوهاج", NameEn = "Sohag" }
			);
		}
		 public static void Productcategoryseed(this ModelBuilder builder)
		{
			builder.Entity<ProductCategory>().HasData(
				new ProductCategory { ID = Guid.NewGuid(), Catagory = "ملابس " },
				new ProductCategory { ID = Guid.NewGuid(), Catagory = "الاغذية" },
				new ProductCategory { ID = Guid.NewGuid(), Catagory = "الآلكترونيات" },
                new ProductCategory { ID = Guid.NewGuid(), Catagory = "الاجهزة المنزلية  " },
                new ProductCategory { ID = Guid.NewGuid(), Catagory = "المشروبات  " },
                new ProductCategory { ID = Guid.NewGuid(), Catagory = "العناية المنزلية  " },
                new ProductCategory { ID = Guid.NewGuid(), Catagory = " منتجات الاطفال" },
                new ProductCategory { ID = Guid.NewGuid(), Catagory = "مستلزمات المنزل   " },
                new ProductCategory { ID = Guid.NewGuid(), Catagory = "كتب   " },
                new ProductCategory { ID = Guid.NewGuid(), Catagory = "مستلزمات السيارات  " },
                new ProductCategory { ID = Guid.NewGuid(), Catagory = "العاب فيديو  " }





                );
			

		}

		public static void SeedCity( this ModelBuilder builder )
		{
			builder.Entity<City>().HasData(
				new City { ID = 1, GovernorateId = 1, NameAr = "15 مايو", NameEn = "15 May" },
				new City { ID = 2, GovernorateId = 1, NameAr = "الازبكية", NameEn = "Al Azbakeyah" },
				new City { ID = 3, GovernorateId = 1, NameAr = "البساتين", NameEn = "Al Basatin" },
				new City { ID = 4, GovernorateId = 1, NameAr = "التبين", NameEn = "Tebin" },
				new City { ID = 5, GovernorateId = 1, NameAr = "الخليفة", NameEn = "El-Khalifa" },
				new City { ID = 6, GovernorateId = 1, NameAr = "الدراسة", NameEn = "El darrasa" },
				new City { ID = 7, GovernorateId = 1, NameAr = "الدرب الاحمر", NameEn = "Aldarb Alahmar" },
				new City { ID = 8, GovernorateId = 1, NameAr = "الزاوية الحمراء", NameEn = "Zawya al-Hamra" },
				new City { ID = 9, GovernorateId = 1, NameAr = "الزيتون", NameEn = "El-Zaytoun" },
				new City { ID = 10, GovernorateId = 1, NameAr = "الساحل", NameEn = "Sahel" },
				new City { ID = 11, GovernorateId = 1, NameAr = "السلام", NameEn = "El Salam" },
				new City { ID = 12, GovernorateId = 1, NameAr = "السيدة زينب", NameEn = "Sayeda Zeinab" },
				new City { ID = 13, GovernorateId = 1, NameAr = "الشرابية", NameEn = "El Sharabeya" },
				new City { ID = 14, GovernorateId = 1, NameAr = "مدينة الشروق", NameEn = "Shorouk" },
				new City { ID = 15, GovernorateId = 1, NameAr = "الظاهر", NameEn = "El Daher" },
				new City { ID = 16, GovernorateId = 1, NameAr = "العتبة", NameEn = "Ataba" },
				new City { ID = 17, GovernorateId = 1, NameAr = "القاهرة الجديدة", NameEn = "New Cairo" },
				new City { ID = 18, GovernorateId = 1, NameAr = "المرج", NameEn = "El Marg" },
				new City { ID = 19, GovernorateId = 1, NameAr = "عزبة النخل", NameEn = "Ezbet el Nakhl" },
				new City { ID = 20, GovernorateId = 1, NameAr = "المطرية", NameEn = "Matareya" },
				new City { ID = 21, GovernorateId = 1, NameAr = "المعادى", NameEn = "Maadi" },
				new City { ID = 22, GovernorateId = 1, NameAr = "المعصرة", NameEn = "Maasara" },
				new City { ID = 23, GovernorateId = 1, NameAr = "المقطم", NameEn = "Mokattam" },
				new City { ID = 24, GovernorateId = 1, NameAr = "المنيل", NameEn = "Manyal" },
				new City { ID = 25, GovernorateId = 1, NameAr = "الموسكى", NameEn = "Mosky" },
				new City { ID = 26, GovernorateId = 1, NameAr = "النزهة", NameEn = "Nozha" },
				new City { ID = 27, GovernorateId = 1, NameAr = "الوايلى", NameEn = "Waily" },
				new City { ID = 28, GovernorateId = 1, NameAr = "باب الشعرية", NameEn = "Bab al-Shereia" },
				new City { ID = 29, GovernorateId = 1, NameAr = "بولاق", NameEn = "Bolaq" },
				new City { ID = 30, GovernorateId = 1, NameAr = "جاردن سيتى", NameEn = "Garden City" },
				new City { ID = 31, GovernorateId = 1, NameAr = "حدائق القبة", NameEn = "Hadayek El-Kobba" },
				new City { ID = 32, GovernorateId = 1, NameAr = "حلوان", NameEn = "Helwan" },
				new City { ID = 33, GovernorateId = 1, NameAr = "دار السلام", NameEn = "Dar Al Salam" },
				new City { ID = 34, GovernorateId = 1, NameAr = "شبرا", NameEn = "Shubra" },
				new City { ID = 35, GovernorateId = 1, NameAr = "طره", NameEn = "Tura" },
				new City { ID = 36, GovernorateId = 1, NameAr = "عابدين", NameEn = "Abdeen" },
				new City { ID = 37, GovernorateId = 1, NameAr = "عباسية", NameEn = "Abaseya" },
				new City { ID = 38, GovernorateId = 1, NameAr = "عين شمس", NameEn = "Ain Shams" },
				new City { ID = 39, GovernorateId = 1, NameAr = "مدينة نصر", NameEn = "Nasr City" },
				new City { ID = 40, GovernorateId = 1, NameAr = "مصر الجديدة", NameEn = "New Heliopolis" },
				new City { ID = 41, GovernorateId = 1, NameAr = "مصر القديمة", NameEn = "Masr Al Qadima" },
				new City { ID = 42, GovernorateId = 1, NameAr = "منشية ناصر", NameEn = "Mansheya Nasir" },
				new City { ID = 43, GovernorateId = 1, NameAr = "مدينة بدر", NameEn = "Badr City" },
				new City { ID = 44, GovernorateId = 1, NameAr = "مدينة العبور", NameEn = "Obour City" },
				new City { ID = 45, GovernorateId = 1, NameAr = "وسط البلد", NameEn = "Cairo Downtown" },
				new City { ID = 46, GovernorateId = 1, NameAr = "الزمالك", NameEn = "Zamalek" },
				new City { ID = 47, GovernorateId = 1, NameAr = "قصر النيل", NameEn = "Kasr El Nile" },
				new City { ID = 48, GovernorateId = 1, NameAr = "الرحاب", NameEn = "Rehab" },
				new City { ID = 49, GovernorateId = 1, NameAr = "القطامية", NameEn = "Katameya" },
				new City { ID = 50, GovernorateId = 1, NameAr = "مدينتي", NameEn = "Madinty" },
				new City { ID = 51, GovernorateId = 1, NameAr = "روض الفرج", NameEn = "Rod Alfarag" },
				new City { ID = 52, GovernorateId = 1, NameAr = "شيراتون", NameEn = "Sheraton" },
				new City { ID = 53, GovernorateId = 1, NameAr = "الجمالية", NameEn = "El-Gamaleya" },
				new City { ID = 54, GovernorateId = 1, NameAr = "العاشر من رمضان", NameEn = "10th of Ramadan City" },
				new City { ID = 55, GovernorateId = 1, NameAr = "الحلمية", NameEn = "Helmeyat Alzaytoun" },
				new City { ID = 56, GovernorateId = 1, NameAr = "النزهة الجديدة", NameEn = "New Nozha" },
				new City { ID = 57, GovernorateId = 1, NameAr = "العاصمة الإدارية", NameEn = "Capital New" },
				new City { ID = 58, GovernorateId = 2, NameAr = "الجيزة", NameEn = "Giza" },
				new City { ID = 59, GovernorateId = 2, NameAr = "السادس من أكتوبر", NameEn = "Sixth of October" },
				new City { ID = 60, GovernorateId = 2, NameAr = "الشيخ زايد", NameEn = "Cheikh Zayed" },
				new City { ID = 61, GovernorateId = 2, NameAr = "الحوامدية", NameEn = "Hawamdiyah" },
				new City { ID = 62, GovernorateId = 2, NameAr = "البدرشين", NameEn = "Al Badrasheen" },
				new City { ID = 63, GovernorateId = 2, NameAr = "الصف", NameEn = "Saf" },
				new City { ID = 64, GovernorateId = 2, NameAr = "أطفيح", NameEn = "Atfih" },
				new City { ID = 65, GovernorateId = 2, NameAr = "العياط", NameEn = "Al Ayat" },
				new City { ID = 66, GovernorateId = 2, NameAr = "الباويطي", NameEn = "Al-Bawaiti" },
				new City { ID = 67, GovernorateId = 2, NameAr = "منشأة القناطر", NameEn = "ManshiyetAl Qanater" },
				new City { ID = 68, GovernorateId = 2, NameAr = "أوسيم", NameEn = "Oaseem" },
				new City { ID = 69, GovernorateId = 2, NameAr = "كرداسة", NameEn = "Kerdasa" },
				new City { ID = 70, GovernorateId = 2, NameAr = "أبو النمرس", NameEn = "Abu Nomros" },
				new City { ID = 71, GovernorateId = 2, NameAr = "كفر غطاطي", NameEn = "Kafr Ghati" },
				new City { ID = 72, GovernorateId = 2, NameAr = "منشأة البكاري", NameEn = "Manshiyet Al Bakari" },
				new City { ID = 73, GovernorateId = 2, NameAr = "الدقى", NameEn = "Dokki" },
				new City { ID = 74, GovernorateId = 2, NameAr = "العجوزة", NameEn = "Agouza" },
				new City { ID = 75, GovernorateId = 2, NameAr = "الهرم", NameEn = "Haram" },
				new City { ID = 76, GovernorateId = 2, NameAr = "الوراق", NameEn = "Warraq" },
				new City { ID = 77, GovernorateId = 2, NameAr = "امبابة", NameEn = "Imbaba" },
				new City { ID = 78, GovernorateId = 2, NameAr = "بولاق الدكرور", NameEn = "Boulaq Dakrour" },
				new City { ID = 79, GovernorateId = 2, NameAr = "الواحات البحرية", NameEn = "Al Wahat Al Baharia" },
				new City { ID = 80, GovernorateId = 2, NameAr = "العمرانية", NameEn = "Omraneya" },
				new City { ID = 81, GovernorateId = 2, NameAr = "المنيب", NameEn = "Moneeb" },
				new City { ID = 82, GovernorateId = 2, NameAr = "بين السرايات", NameEn = "Bin Alsarayat" },
				new City { ID = 83, GovernorateId = 2, NameAr = "الكيت كات", NameEn = "Kit Kat" },
				new City { ID = 84, GovernorateId = 2, NameAr = "المهندسين", NameEn = "Mohandessin" },
				new City { ID = 85, GovernorateId = 2, NameAr = "فيصل", NameEn = "Faisal" },
				new City { ID = 86, GovernorateId = 2, NameAr = "أبو رواش", NameEn = "Abu Rawash" },
				new City { ID = 87, GovernorateId = 2, NameAr = "حدائق الأهرام", NameEn = "Hadayek Alahram" },
				new City { ID = 88, GovernorateId = 2, NameAr = "الحرانية", NameEn = "Haraneya" },
				new City { ID = 89, GovernorateId = 2, NameAr = "حدائق اكتوبر", NameEn = "Hadayek October" },
				new City { ID = 90, GovernorateId = 2, NameAr = "صفط اللبن", NameEn = "Saft Allaban" },
				new City { ID = 91, GovernorateId = 2, NameAr = "القرية الذكية", NameEn = "Smart Village" },
				new City { ID = 92, GovernorateId = 2, NameAr = "ارض اللواء", NameEn = "Ard Ellwaa" },
				new City { ID = 93, GovernorateId = 3, NameAr = "ابو قير", NameEn = "Abu Qir" },
				new City { ID = 94, GovernorateId = 3, NameAr = "الابراهيمية", NameEn = "Al Ibrahimeyah" },
				new City { ID = 95, GovernorateId = 3, NameAr = "الأزاريطة", NameEn = "Azarita" },
				new City { ID = 96, GovernorateId = 3, NameAr = "الانفوشى", NameEn = "Anfoushi" },
				new City { ID = 97, GovernorateId = 3, NameAr = "الدخيلة", NameEn = "Dekheila" },
				new City { ID = 98, GovernorateId = 3, NameAr = "السيوف", NameEn = "El Soyof" },
				new City { ID = 99, GovernorateId = 3, NameAr = "العامرية", NameEn = "Ameria" },
				new City { ID = 100, GovernorateId = 3, NameAr = "اللبان", NameEn = "El Labban" },
				new City { ID = 101, GovernorateId = 3, NameAr = "المفروزة", NameEn = "Al Mafrouza" },
				new City { ID = 102, GovernorateId = 3, NameAr = "المنتزه", NameEn = "El Montaza" },
				new City { ID = 103, GovernorateId = 3, NameAr = "المنشية", NameEn = "Mansheya" },
				new City { ID = 104, GovernorateId = 3, NameAr = "الناصرية", NameEn = "Naseria" },
				new City { ID = 105, GovernorateId = 3, NameAr = "امبروزو", NameEn = "Ambrozo" },
				new City { ID = 106, GovernorateId = 3, NameAr = "باب شرق", NameEn = "Bab Sharq" },
				new City { ID = 107, GovernorateId = 3, NameAr = "برج العرب", NameEn = "Bourj Alarab" },
				new City { ID = 108, GovernorateId = 3, NameAr = "ستانلى", NameEn = "Stanley" },
				new City { ID = 109, GovernorateId = 3, NameAr = "سموحة", NameEn = "Smouha" },
				new City { ID = 110, GovernorateId = 3, NameAr = "سيدى بشر", NameEn = "Sidi Bishr" },
				new City { ID = 111, GovernorateId = 3, NameAr = "شدس", NameEn = "Shads" },
				new City { ID = 112, GovernorateId = 3, NameAr = "غيط العنب", NameEn = "Gheet Alenab" },
				new City { ID = 113, GovernorateId = 3, NameAr = "فلمينج", NameEn = "Fleming" },
				new City { ID = 114, GovernorateId = 3, NameAr = "فيكتوريا", NameEn = "Victoria" },
				new City { ID = 115, GovernorateId = 3, NameAr = "كامب شيزار", NameEn = "Camp Shizar" },
				new City { ID = 116, GovernorateId = 3, NameAr = "كرموز", NameEn = "Karmooz" },
				new City { ID = 117, GovernorateId = 3, NameAr = "محطة الرمل", NameEn = "Mahta Alraml" },
				new City { ID = 118, GovernorateId = 3, NameAr = "مينا البصل", NameEn = "Mina El-Basal" },
				new City { ID = 119, GovernorateId = 3, NameAr = "العصافرة", NameEn = "Asafra" },
				new City { ID = 120, GovernorateId = 3, NameAr = "العجمي", NameEn = "Agamy" },
				new City { ID = 121, GovernorateId = 3, NameAr = "بكوس", NameEn = "Bakos" },
				new City { ID = 122, GovernorateId = 3, NameAr = "بولكلي", NameEn = "Boulkly" },
				new City { ID = 123, GovernorateId = 3, NameAr = "كليوباترا", NameEn = "Cleopatra" },
				new City { ID = 124, GovernorateId = 3, NameAr = "جليم", NameEn = "Glim" },
				new City { ID = 125, GovernorateId = 3, NameAr = "المعمورة", NameEn = "Al Mamurah" },
				new City { ID = 126, GovernorateId = 3, NameAr = "المندرة", NameEn = "Al Mandara" },
				new City { ID = 127, GovernorateId = 3, NameAr = "محرم بك", NameEn = "Moharam Bek" },
				new City { ID = 128, GovernorateId = 3, NameAr = "الشاطبي", NameEn = "Elshatby" },
				new City { ID = 129, GovernorateId = 3, NameAr = "سيدي جابر", NameEn = "Sidi Gaber" },
				new City { ID = 130, GovernorateId = 3, NameAr = "الساحل الشمالي", NameEn = "North Coast Sahel" },
				new City { ID = 131, GovernorateId = 3, NameAr = "الحضرة", NameEn = "Alhadra" },
				new City { ID = 132, GovernorateId = 3, NameAr = "العطارين", NameEn = "Alattarin" },
				new City { ID = 133, GovernorateId = 3, NameAr = "سيدي كرير", NameEn = "Sidi Kerir" },
				new City { ID = 134, GovernorateId = 3, NameAr = "الجمرك", NameEn = "Elgomrok" },
				new City { ID = 135, GovernorateId = 3, NameAr = "المكس", NameEn = "Al Max" },
				new City { ID = 136, GovernorateId = 3, NameAr = "مارينا", NameEn = "Marina" },
				new City { ID = 137, GovernorateId = 4, NameAr = "المنصورة", NameEn = "Mansoura" },
				new City { ID = 138, GovernorateId = 4, NameAr = "طلخا", NameEn = "Talkha" },
				new City { ID = 139, GovernorateId = 4, NameAr = "ميت غمر", NameEn = "Mitt Ghamr" },
				new City { ID = 140, GovernorateId = 4, NameAr = "دكرنس", NameEn = "Dekernes" },
				new City { ID = 141, GovernorateId = 4, NameAr = "أجا", NameEn = "Aga" },
				new City { ID = 142, GovernorateId = 4, NameAr = "منية النصر", NameEn = "Menia El Nasr" },
				new City { ID = 143, GovernorateId = 4, NameAr = "السنبلاوين", NameEn = "Sinbillawin" },
				new City { ID = 144, GovernorateId = 4, NameAr = "الكردي", NameEn = "El Kurdi" },
				new City { ID = 145, GovernorateId = 4, NameAr = "بني عبيد", NameEn = "Bani Ubaid" },
				new City { ID = 146, GovernorateId = 4, NameAr = "المنزلة", NameEn = "Al Manzala" },
				new City { ID = 147, GovernorateId = 4, NameAr = "تمي الأمديد", NameEn = "tami al'amdid" },
				new City { ID = 148, GovernorateId = 4, NameAr = "الجمالية", NameEn = "aljamalia" },
				new City { ID = 149, GovernorateId = 4, NameAr = "شربين", NameEn = "Sherbin" },
				new City { ID = 150, GovernorateId = 4, NameAr = "المطرية", NameEn = "Mataria" },
				new City { ID = 151, GovernorateId = 4, NameAr = "بلقاس", NameEn = "Belqas" },
				new City { ID = 152, GovernorateId = 4, NameAr = "ميت سلسيل", NameEn = "Meet Salsil" },
				new City { ID = 153, GovernorateId = 4, NameAr = "جمصة", NameEn = "Gamasa" },
				new City { ID = 154, GovernorateId = 4, NameAr = "محلة دمنة", NameEn = "Mahalat Damana" },
				new City { ID = 155, GovernorateId = 4, NameAr = "نبروه", NameEn = "Nabroh" },
				new City { ID = 156, GovernorateId = 5, NameAr = "الغردقة", NameEn = "Hurghada" },
				new City { ID = 157, GovernorateId = 5, NameAr = "رأس غارب", NameEn = "Ras Ghareb" },
				new City { ID = 158, GovernorateId = 5, NameAr = "سفاجا", NameEn = "Safaga" },
				new City { ID = 159, GovernorateId = 5, NameAr = "القصير", NameEn = "El Qusiar" },
				new City { ID = 160, GovernorateId = 5, NameAr = "مرسى علم", NameEn = "Marsa Alam" },
				new City { ID = 161, GovernorateId = 5, NameAr = "الشلاتين", NameEn = "Shalatin" },
				new City { ID = 162, GovernorateId = 5, NameAr = "حلايب", NameEn = "Halaib" },
				new City { ID = 163, GovernorateId = 5, NameAr = "الدهار", NameEn = "Aldahar" },
				new City { ID = 164, GovernorateId = 6, NameAr = "دمنهور", NameEn = "Damanhour" },
				new City { ID = 165, GovernorateId = 6, NameAr = "كفر الدوار", NameEn = "Kafr El Dawar" },
				new City { ID = 166, GovernorateId = 6, NameAr = "رشيد", NameEn = "Rashid" },
				new City { ID = 167, GovernorateId = 6, NameAr = "إدكو", NameEn = "Edco" },
				new City { ID = 168, GovernorateId = 6, NameAr = "أبو المطامير", NameEn = "Abu al-Matamir" },
				new City { ID = 169, GovernorateId = 6, NameAr = "أبو حمص", NameEn = "Abu Homs" },
				new City { ID = 170, GovernorateId = 6, NameAr = "الدلنجات", NameEn = "Delengat" },
				new City { ID = 171, GovernorateId = 6, NameAr = "المحمودية", NameEn = "Mahmoudiyah" },
				new City { ID = 172, GovernorateId = 6, NameAr = "الرحمانية", NameEn = "Rahmaniyah" },
				new City { ID = 173, GovernorateId = 6, NameAr = "إيتاي البارود", NameEn = "Itai Baroud" },
				new City { ID = 174, GovernorateId = 6, NameAr = "حوش عيسى", NameEn = "Housh Eissa" },
				new City { ID = 175, GovernorateId = 6, NameAr = "شبراخيت", NameEn = "Shubrakhit" },
				new City { ID = 176, GovernorateId = 6, NameAr = "كوم حمادة", NameEn = "Kom Hamada" },
				new City { ID = 177, GovernorateId = 6, NameAr = "بدر", NameEn = "Badr" },
				new City { ID = 178, GovernorateId = 6, NameAr = "وادي النطرون", NameEn = "Wadi Natrun" },
				new City { ID = 179, GovernorateId = 6, NameAr = "النوبارية الجديدة", NameEn = "New Nubaria" },
				new City { ID = 180, GovernorateId = 6, NameAr = "النوبارية", NameEn = "Alnoubareya" },
				new City { ID = 181, GovernorateId = 7, NameAr = "الفيوم", NameEn = "Fayoum" },
				new City { ID = 182, GovernorateId = 7, NameAr = "الفيوم الجديدة", NameEn = "Fayoum El Gedida" },
				new City { ID = 183, GovernorateId = 7, NameAr = "طامية", NameEn = "Tamiya" },
				new City { ID = 184, GovernorateId = 7, NameAr = "سنورس", NameEn = "Snores" },
				new City { ID = 185, GovernorateId = 7, NameAr = "إطسا", NameEn = "Etsa" },
				new City { ID = 186, GovernorateId = 7, NameAr = "إبشواي", NameEn = "Epschway" },
				new City { ID = 187, GovernorateId = 7, NameAr = "يوسف الصديق", NameEn = "Yusuf El Sediaq" },
				new City { ID = 188, GovernorateId = 7, NameAr = "الحادقة", NameEn = "Hadqa" },
				new City { ID = 189, GovernorateId = 7, NameAr = "اطسا", NameEn = "Atsa" },
				new City { ID = 190, GovernorateId = 7, NameAr = "الجامعة", NameEn = "Algamaa" },
				new City { ID = 191, GovernorateId = 7, NameAr = "السيالة", NameEn = "Sayala" },
				new City { ID = 192, GovernorateId = 8, NameAr = "طنطا", NameEn = "Tanta" },
				new City { ID = 193, GovernorateId = 8, NameAr = "المحلة الكبرى", NameEn = "Al Mahalla Al Kobra" },
				new City { ID = 194, GovernorateId = 8, NameAr = "كفر الزيات", NameEn = "Kafr El Zayat" },
				new City { ID = 195, GovernorateId = 8, NameAr = "زفتى", NameEn = "Zefta" },
				new City { ID = 196, GovernorateId = 8, NameAr = "السنطة", NameEn = "El Santa" },
				new City { ID = 197, GovernorateId = 8, NameAr = "قطور", NameEn = "Qutour" },
				new City { ID = 198, GovernorateId = 8, NameAr = "بسيون", NameEn = "Basion" },
				new City { ID = 199, GovernorateId = 8, NameAr = "سمنود", NameEn = "Samannoud" },
				new City { ID = 200, GovernorateId = 9, NameAr = "الإسماعيلية", NameEn = "Ismailia" },
				new City { ID = 201, GovernorateId = 9, NameAr = "فايد", NameEn = "Fayed" },
				new City { ID = 202, GovernorateId = 9, NameAr = "القنطرة شرق", NameEn = "Qantara Sharq" },
				new City { ID = 203, GovernorateId = 9, NameAr = "القنطرة غرب", NameEn = "Qantara Gharb" },
				new City { ID = 204, GovernorateId = 9, NameAr = "التل الكبير", NameEn = "El Tal El Kabier" },
				new City { ID = 205, GovernorateId = 9, NameAr = "أبو صوير", NameEn = "Abu Sawir" },
				new City { ID = 206, GovernorateId = 9, NameAr = "القصاصين الجديدة", NameEn = "Kasasien El Gedida" },
				new City { ID = 207, GovernorateId = 9, NameAr = "نفيشة", NameEn = "Nefesha" },
				new City { ID = 208, GovernorateId = 9, NameAr = "الشيخ زايد", NameEn = "Sheikh Zayed" },
				new City { ID = 209, GovernorateId = 10, NameAr = "شبين الكوم", NameEn = "Shbeen El Koom" },
				new City { ID = 210, GovernorateId = 10, NameAr = "مدينة السادات", NameEn = "Sadat City" },
				new City { ID = 211, GovernorateId = 10, NameAr = "منوف", NameEn = "Menouf" },
				new City { ID = 212, GovernorateId = 10, NameAr = "سرس الليان", NameEn = "Sars El-Layan" },
				new City { ID = 213, GovernorateId = 10, NameAr = "أشمون", NameEn = "Ashmon" },
				new City { ID = 214, GovernorateId = 10, NameAr = "الباجور", NameEn = "Al Bagor" },
				new City { ID = 215, GovernorateId = 10, NameAr = "قويسنا", NameEn = "Quesna" },
				new City { ID = 216, GovernorateId = 10, NameAr = "بركة السبع", NameEn = "Berkat El Saba" },
				new City { ID = 217, GovernorateId = 10, NameAr = "تلا", NameEn = "Tala" },
				new City { ID = 218, GovernorateId = 10, NameAr = "الشهداء", NameEn = "Al Shohada" },
				new City { ID = 219, GovernorateId = 11, NameAr = "المنيا", NameEn = "Minya" },
				new City { ID = 220, GovernorateId = 11, NameAr = "المنيا الجديدة", NameEn = "Minya El Gedida" },
				new City { ID = 221, GovernorateId = 11, NameAr = "العدوة", NameEn = "El Adwa" },
				new City { ID = 222, GovernorateId = 11, NameAr = "مغاغة", NameEn = "Magagha" },
				new City { ID = 223, GovernorateId = 11, NameAr = "بني مزار", NameEn = "Bani Mazar" },
				new City { ID = 224, GovernorateId = 11, NameAr = "مطاي", NameEn = "Mattay" },
				new City { ID = 225, GovernorateId = 11, NameAr = "سمالوط", NameEn = "Samalut" },
				new City { ID = 226, GovernorateId = 11, NameAr = "المدينة الفكرية", NameEn = "Madinat El Fekria" },
				new City { ID = 227, GovernorateId = 11, NameAr = "ملوي", NameEn = "Meloy" },
				new City { ID = 228, GovernorateId = 11, NameAr = "دير مواس", NameEn = "Deir Mawas" },
				new City { ID = 229, GovernorateId = 11, NameAr = "ابو قرقاص", NameEn = "Abu Qurqas" },
				new City { ID = 230, GovernorateId = 11, NameAr = "ارض سلطان", NameEn = "Ard Sultan" },
				new City { ID = 231, GovernorateId = 12, NameAr = "بنها", NameEn = "Banha" },
				new City { ID = 232, GovernorateId = 12, NameAr = "قليوب", NameEn = "Qalyub" },
				new City { ID = 233, GovernorateId = 12, NameAr = "شبرا الخيمة", NameEn = "Shubra Al Khaimah" },
				new City { ID = 234, GovernorateId = 12, NameAr = "القناطر الخيرية", NameEn = "Al Qanater Charity" },
				new City { ID = 235, GovernorateId = 12, NameAr = "الخانكة", NameEn = "Khanka" },
				new City { ID = 236, GovernorateId = 12, NameAr = "كفر شكر", NameEn = "Kafr Shukr" },
				new City { ID = 237, GovernorateId = 12, NameAr = "طوخ", NameEn = "Tukh" },
				new City { ID = 238, GovernorateId = 12, NameAr = "قها", NameEn = "Qaha" },
				new City { ID = 239, GovernorateId = 12, NameAr = "العبور", NameEn = "Obour" },
				new City { ID = 240, GovernorateId = 12, NameAr = "الخصوص", NameEn = "Khosous" },
				new City { ID = 241, GovernorateId = 12, NameAr = "شبين القناطر", NameEn = "Shibin Al Qanater" },
				new City { ID = 242, GovernorateId = 12, NameAr = "مسطرد", NameEn = "Mostorod" },
				new City { ID = 243, GovernorateId = 13, NameAr = "الخارجة", NameEn = "El Kharga" },
				new City { ID = 244, GovernorateId = 13, NameAr = "باريس", NameEn = "Paris" },
				new City { ID = 245, GovernorateId = 13, NameAr = "موط", NameEn = "Mout" },
				new City { ID = 246, GovernorateId = 13, NameAr = "الفرافرة", NameEn = "Farafra" },
				new City { ID = 247, GovernorateId = 13, NameAr = "بلاط", NameEn = "Balat" },
				new City { ID = 248, GovernorateId = 13, NameAr = "الداخلة", NameEn = "Dakhla" },
				new City { ID = 249, GovernorateId = 14, NameAr = "السويس", NameEn = "Suez" },
				new City { ID = 250, GovernorateId = 14, NameAr = "الجناين", NameEn = "Alganayen" },
				new City { ID = 251, GovernorateId = 14, NameAr = "عتاقة", NameEn = "Ataqah" },
				new City { ID = 252, GovernorateId = 14, NameAr = "العين السخنة", NameEn = "Ain Sokhna" },
				new City { ID = 253, GovernorateId = 14, NameAr = "فيصل", NameEn = "Faysal" },
				new City { ID = 254, GovernorateId = 15, NameAr = "أسوان", NameEn = "Aswan" },
				new City { ID = 255, GovernorateId = 15, NameAr = "أسوان الجديدة", NameEn = "Aswan El Gedida" },
				new City { ID = 256, GovernorateId = 15, NameAr = "دراو", NameEn = "Drau" },
				new City { ID = 257, GovernorateId = 15, NameAr = "كوم أمبو", NameEn = "Kom Ombo" },
				new City { ID = 258, GovernorateId = 15, NameAr = "نصر النوبة", NameEn = "Nasr Al Nuba" },
				new City { ID = 259, GovernorateId = 15, NameAr = "كلابشة", NameEn = "Kalabsha" },
				new City { ID = 260, GovernorateId = 15, NameAr = "إدفو", NameEn = "Edfu" },
				new City { ID = 261, GovernorateId = 15, NameAr = "الرديسية", NameEn = "Al-Radisiyah" },
				new City { ID = 262, GovernorateId = 15, NameAr = "البصيلية", NameEn = "Al Basilia" },
				new City { ID = 263, GovernorateId = 15, NameAr = "السباعية", NameEn = "Al Sibaeia" },
				new City { ID = 264, GovernorateId = 15, NameAr = "ابوسمبل السياحية", NameEn = "Abo Simbl Al Siyahia" },
				new City { ID = 265, GovernorateId = 15, NameAr = "مرسى علم", NameEn = "Marsa Alam" },
				new City { ID = 266, GovernorateId = 16, NameAr = "أسيوط", NameEn = "Assiut" },
				new City { ID = 267, GovernorateId = 16, NameAr = "أسيوط الجديدة", NameEn = "Assiut El Gedida" },
				new City { ID = 268, GovernorateId = 16, NameAr = "ديروط", NameEn = "Dayrout" },
				new City { ID = 269, GovernorateId = 16, NameAr = "منفلوط", NameEn = "Manfalut" },
				new City { ID = 270, GovernorateId = 16, NameAr = "القوصية", NameEn = "Qusiya" },
				new City { ID = 271, GovernorateId = 16, NameAr = "أبنوب", NameEn = "Abnoub" },
				new City { ID = 272, GovernorateId = 16, NameAr = "أبو تيج", NameEn = "Abu Tig" },
				new City { ID = 273, GovernorateId = 16, NameAr = "الغنايم", NameEn = "El Ghanaim" },
				new City { ID = 274, GovernorateId = 16, NameAr = "ساحل سليم", NameEn = "Sahel Selim" },
				new City { ID = 275, GovernorateId = 16, NameAr = "البداري", NameEn = "El Badari" },
				new City { ID = 276, GovernorateId = 16, NameAr = "صدفا", NameEn = "Sidfa" },
				new City { ID = 277, GovernorateId = 17, NameAr = "بني سويف", NameEn = "Bani Sweif" },
				new City { ID = 278, GovernorateId = 17, NameAr = "بني سويف الجديدة", NameEn = "Beni Suef El Gedida" },
				new City { ID = 279, GovernorateId = 17, NameAr = "الواسطى", NameEn = "Al Wasta" },
				new City { ID = 280, GovernorateId = 17, NameAr = "ناصر", NameEn = "Naser" },
				new City { ID = 281, GovernorateId = 17, NameAr = "إهناسيا", NameEn = "Ehnasia" },
				new City { ID = 282, GovernorateId = 17, NameAr = "ببا", NameEn = "beba" },
				new City { ID = 283, GovernorateId = 17, NameAr = "الفشن", NameEn = "Fashn" },
				new City { ID = 284, GovernorateId = 17, NameAr = "سمسطا", NameEn = "Somasta" },
				new City { ID = 285, GovernorateId = 17, NameAr = "الاباصيرى", NameEn = "Alabbaseri" },
				new City { ID = 286, GovernorateId = 17, NameAr = "مقبل", NameEn = "Mokbel" },
				new City { ID = 287, GovernorateId = 18, NameAr = "بورسعيد", NameEn = "PorSaid" },
				new City { ID = 288, GovernorateId = 18, NameAr = "بورفؤاد", NameEn = "Port Fouad" },
				new City { ID = 289, GovernorateId = 18, NameAr = "العرب", NameEn = "Alarab" },
				new City { ID = 290, GovernorateId = 18, NameAr = "حى الزهور", NameEn = "Zohour" },
				new City { ID = 291, GovernorateId = 18, NameAr = "حى الشرق", NameEn = "Alsharq" },
				new City { ID = 292, GovernorateId = 18, NameAr = "حى الضواحى", NameEn = "Aldawahi" },
				new City { ID = 293, GovernorateId = 18, NameAr = "حى المناخ", NameEn = "Almanakh" },
				new City { ID = 294, GovernorateId = 18, NameAr = "حى مبارك", NameEn = "Mubarak" },
				new City { ID = 295, GovernorateId = 19, NameAr = "دمياط", NameEn = "Damietta" },
				new City { ID = 296, GovernorateId = 19, NameAr = "دمياط الجديدة", NameEn = "New Damietta" },
				new City { ID = 297, GovernorateId = 19, NameAr = "رأس البر", NameEn = "Ras El Bar" },
				new City { ID = 298, GovernorateId = 19, NameAr = "فارسكور", NameEn = "Faraskour" },
				new City { ID = 299, GovernorateId = 19, NameAr = "الزرقا", NameEn = "Zarqa" },
				new City { ID = 300, GovernorateId = 19, NameAr = "السرو", NameEn = "alsaru" },
				new City { ID = 301, GovernorateId = 19, NameAr = "الروضة", NameEn = "alruwda" },
				new City { ID = 302, GovernorateId = 19, NameAr = "كفر البطيخ", NameEn = "Kafr El-Batikh" },
				new City { ID = 303, GovernorateId = 19, NameAr = "عزبة البرج", NameEn = "Azbet Al Burg" },
				new City { ID = 304, GovernorateId = 19, NameAr = "ميت أبو غالب", NameEn = "Meet Abou Ghalib" },
				new City { ID = 305, GovernorateId = 19, NameAr = "كفر سعد", NameEn = "Kafr Saad" },
				new City { ID = 306, GovernorateId = 20, NameAr = "الزقازيق", NameEn = "Zagazig" },
				new City { ID = 307, GovernorateId = 20, NameAr = "العاشر من رمضان", NameEn = "Al Ashr Men Ramadan" },
				new City { ID = 308, GovernorateId = 20, NameAr = "منيا القمح", NameEn = "Minya Al Qamh" },
				new City { ID = 309, GovernorateId = 20, NameAr = "بلبيس", NameEn = "Belbeis" },
				new City { ID = 310, GovernorateId = 20, NameAr = "مشتول السوق", NameEn = "Mashtoul El Souq" },
				new City { ID = 311, GovernorateId = 20, NameAr = "القنايات", NameEn = "Qenaiat" },
				new City { ID = 312, GovernorateId = 20, NameAr = "أبو حماد", NameEn = "Abu Hammad" },
				new City { ID = 313, GovernorateId = 20, NameAr = "القرين", NameEn = "El Qurain" },
				new City { ID = 314, GovernorateId = 20, NameAr = "ههيا", NameEn = "Hehia" },
				new City { ID = 315, GovernorateId = 20, NameAr = "أبو كبير", NameEn = "Abu Kabir" },
				new City { ID = 316, GovernorateId = 20, NameAr = "فاقوس", NameEn = "Faccus" },
				new City { ID = 317, GovernorateId = 20, NameAr = "الصالحية الجديدة", NameEn = "El Salihia El Gedida" },
				new City { ID = 318, GovernorateId = 20, NameAr = "الإبراهيمية", NameEn = "Al Ibrahimiyah" },
				new City { ID = 319, GovernorateId = 20, NameAr = "ديرب نجم", NameEn = "Deirb Negm" },
				new City { ID = 320, GovernorateId = 20, NameAr = "كفر صقر", NameEn = "Kafr Saqr" },
				new City { ID = 321, GovernorateId = 20, NameAr = "أولاد صقر", NameEn = "Awlad Saqr" },
				new City { ID = 322, GovernorateId = 20, NameAr = "الحسينية", NameEn = "Husseiniya" },
				new City { ID = 323, GovernorateId = 20, NameAr = "صان الحجر القبلية", NameEn = "san alhajar alqablia" },
				new City { ID = 324, GovernorateId = 20, NameAr = "منشأة أبو عمر", NameEn = "Manshayat Abu Omar" },
				new City { ID = 325, GovernorateId = 21, NameAr = "الطور", NameEn = "Al Toor" },
				new City { ID = 326, GovernorateId = 21, NameAr = "شرم الشيخ", NameEn = "Sharm El-Shaikh" },
				new City { ID = 327, GovernorateId = 21, NameAr = "دهب", NameEn = "Dahab" },
				new City { ID = 328, GovernorateId = 21, NameAr = "نويبع", NameEn = "Nuweiba" },
				new City { ID = 329, GovernorateId = 21, NameAr = "طابا", NameEn = "Taba" },
				new City { ID = 330, GovernorateId = 21, NameAr = "سانت كاترين", NameEn = "Saint Catherine" },
				new City { ID = 331, GovernorateId = 21, NameAr = "أبو رديس", NameEn = "Abu Redis" },
				new City { ID = 332, GovernorateId = 21, NameAr = "أبو زنيمة", NameEn = "Abu Zenaima" },
				new City { ID = 333, GovernorateId = 21, NameAr = "رأس سدر", NameEn = "Ras Sidr" },
				new City { ID = 334, GovernorateId = 22, NameAr = "كفر الشيخ", NameEn = "Kafr El Sheikh" },
				new City { ID = 335, GovernorateId = 22, NameAr = "وسط البلد كفر الشيخ", NameEn = "Kafr El Sheikh Downtown" },
				new City { ID = 336, GovernorateId = 22, NameAr = "دسوق", NameEn = "Desouq" },
				new City { ID = 337, GovernorateId = 22, NameAr = "فوه", NameEn = "Fooh" },
				new City { ID = 338, GovernorateId = 22, NameAr = "مطوبس", NameEn = "Metobas" },
				new City { ID = 339, GovernorateId = 22, NameAr = "برج البرلس", NameEn = "Burg Al Burullus" },
				new City { ID = 340, GovernorateId = 22, NameAr = "بلطيم", NameEn = "Baltim" },
				new City { ID = 341, GovernorateId = 22, NameAr = "مصيف بلطيم", NameEn = "Masief Baltim" },
				new City { ID = 342, GovernorateId = 22, NameAr = "الحامول", NameEn = "Hamol" },
				new City { ID = 343, GovernorateId = 22, NameAr = "بيلا", NameEn = "Bella" },
				new City { ID = 344, GovernorateId = 22, NameAr = "الرياض", NameEn = "Riyadh" },
				new City { ID = 345, GovernorateId = 22, NameAr = "سيدي سالم", NameEn = "Sidi Salm" },
				new City { ID = 346, GovernorateId = 22, NameAr = "قلين", NameEn = "Qellen" },
				new City { ID = 347, GovernorateId = 22, NameAr = "سيدي غازي", NameEn = "Sidi Ghazi" },
				new City { ID = 348, GovernorateId = 23, NameAr = "مرسى مطروح", NameEn = "Marsa Matrouh" },
				new City { ID = 349, GovernorateId = 23, NameAr = "الحمام", NameEn = "El Hamam" },
				new City { ID = 350, GovernorateId = 23, NameAr = "العلمين", NameEn = "Alamein" },
				new City { ID = 351, GovernorateId = 23, NameAr = "الضبعة", NameEn = "Dabaa" },
				new City { ID = 352, GovernorateId = 23, NameAr = "النجيلة", NameEn = "Al-Nagila" },
				new City { ID = 353, GovernorateId = 23, NameAr = "سيدي براني", NameEn = "Sidi Brani" },
				new City { ID = 354, GovernorateId = 23, NameAr = "السلوم", NameEn = "Salloum" },
				new City { ID = 355, GovernorateId = 23, NameAr = "سيوة", NameEn = "Siwa" },
				new City { ID = 356, GovernorateId = 23, NameAr = "مارينا", NameEn = "Marina" },
				new City { ID = 357, GovernorateId = 23, NameAr = "الساحل الشمالى", NameEn = "North Coast" },
				new City { ID = 358, GovernorateId = 24, NameAr = "الأقصر", NameEn = "Luxor" },
				new City { ID = 359, GovernorateId = 24, NameAr = "الأقصر الجديدة", NameEn = "New Luxor" },
				new City { ID = 360, GovernorateId = 24, NameAr = "إسنا", NameEn = "Esna" },
				new City { ID = 361, GovernorateId = 24, NameAr = "طيبة الجديدة", NameEn = "New Tiba" },
				new City { ID = 362, GovernorateId = 24, NameAr = "الزينية", NameEn = "Al ziynia" },
				new City { ID = 363, GovernorateId = 24, NameAr = "البياضية", NameEn = "Al Bayadieh" },
				new City { ID = 364, GovernorateId = 24, NameAr = "القرنة", NameEn = "Al Qarna" },
				new City { ID = 365, GovernorateId = 24, NameAr = "أرمنت", NameEn = "Armant" },
				new City { ID = 366, GovernorateId = 24, NameAr = "الطود", NameEn = "Al Tud" },
				new City { ID = 367, GovernorateId = 25, NameAr = "قنا", NameEn = "Qena" },
				new City { ID = 368, GovernorateId = 25, NameAr = "قنا الجديدة", NameEn = "New Qena" },
				new City { ID = 369, GovernorateId = 25, NameAr = "ابو طشت", NameEn = "Abu Tesht" },
				new City { ID = 370, GovernorateId = 25, NameAr = "نجع حمادي", NameEn = "Nag Hammadi" },
				new City { ID = 371, GovernorateId = 25, NameAr = "دشنا", NameEn = "Deshna" },
				new City { ID = 372, GovernorateId = 25, NameAr = "الوقف", NameEn = "Alwaqf" },
				new City { ID = 373, GovernorateId = 25, NameAr = "قفط", NameEn = "Qaft" },
				new City { ID = 374, GovernorateId = 25, NameAr = "نقادة", NameEn = "Naqada" },
				new City { ID = 375, GovernorateId = 25, NameAr = "فرشوط", NameEn = "Farshout" },
				new City { ID = 376, GovernorateId = 25, NameAr = "قوص", NameEn = "Quos" },
				new City { ID = 377, GovernorateId = 26, NameAr = "العريش", NameEn = "Arish" },
				new City { ID = 378, GovernorateId = 26, NameAr = "الشيخ زويد", NameEn = "Sheikh Zowaid" },
				new City { ID = 379, GovernorateId = 26, NameAr = "نخل", NameEn = "Nakhl" },
				new City { ID = 380, GovernorateId = 26, NameAr = "رفح", NameEn = "Rafah" },
				new City { ID = 381, GovernorateId = 26, NameAr = "بئر العبد", NameEn = "Bir al-Abed" },
				new City { ID = 382, GovernorateId = 26, NameAr = "الحسنة", NameEn = "Al Hasana" },
				new City { ID = 383, GovernorateId = 27, NameAr = "سوهاج", NameEn = "Sohag" },
				new City { ID = 384, GovernorateId = 27, NameAr = "سوهاج الجديدة", NameEn = "Sohag El Gedida" },
				new City { ID = 385, GovernorateId = 27, NameAr = "أخميم", NameEn = "Akhmeem" },
				new City { ID = 386, GovernorateId = 27, NameAr = "أخميم الجديدة", NameEn = "Akhmim El Gedida" },
				new City { ID = 387, GovernorateId = 27, NameAr = "البلينا", NameEn = "Albalina" },
				new City { ID = 388, GovernorateId = 27, NameAr = "المراغة", NameEn = "El Maragha" },
				new City { ID = 389, GovernorateId = 27, NameAr = "المنشأة", NameEn = "almunsha'a" },
				new City { ID = 390, GovernorateId = 27, NameAr = "دار السلام", NameEn = "Dar AISalaam" },
				new City { ID = 391, GovernorateId = 27, NameAr = "جرجا", NameEn = "Gerga" },
				new City { ID = 392, GovernorateId = 27, NameAr = "جهينة الغربية", NameEn = "Jahina Al Gharbia" },
				new City { ID = 393, GovernorateId = 27, NameAr = "ساقلته", NameEn = "Saqilatuh" },
				new City { ID = 394, GovernorateId = 27, NameAr = "طما", NameEn = "Tama" },
				new City { ID = 395, GovernorateId = 27, NameAr = "طهطا", NameEn = "Tahta" },
				new City { ID = 396, GovernorateId = 27, NameAr = "الكوثر", NameEn = "Alkawthar" }
			);
		}

		public static void SeedRequestAndServiceCategories( this ModelBuilder builder )
		{
			builder.Entity<ServiceCategory>().HasData(
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "المحاسبة", NameEn = "Accounting" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "الإعلان والتسويق", NameEn = "Advertising and marketing" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "إستشارات", NameEn = "Consulting " },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات تكنولوجيا المعلومات", NameEn = "Information technology services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات قانونية", NameEn = "Legal services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "إدارة المكاتب", NameEn = "Office management" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات الترجمة", NameEn = "Translation services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "تصميم وتطوير مواقع الويب", NameEn = "Web design and development" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "صيانة سيارات", NameEn = "Car maintenance" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات التجميل", NameEn = "Beauty services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "تقديم الطعام", NameEn = "Catering " },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "رعاية الأطفال", NameEn = "Childcare" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات التنظيف", NameEn = "Cleaning services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "إصلاح الكمبيوتر", NameEn = "Computer repair" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات التوصيل", NameEn = "Delivery services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "التنظيف الجاف", NameEn = "Dry cleaning" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "التخطيط للأحداث", NameEn = "Event planning" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "الخدمات المالية", NameEn = "Financial services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "تدريب اللياقة البدنية", NameEn = "Fitness training" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "توصيل طلبات الطعام", NameEn = "Food delivery" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "تأمين", NameEn = "Insurance" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "العناية بالحديقة", NameEn = "Garden care" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات غسيل الملابس", NameEn = "Laundry services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات صناعة الأقفال", NameEn = "Locksmith services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "الخدمات الطبية", NameEn = "Medical services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات النقل", NameEn = "Transportation services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "رعاية الحيوانات الاليفة", NameEn = "Pet care" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "الخدمات البيطرية", NameEn = "Veterinary services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "سباكة", NameEn = "Plumbing" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "كهرباء", NameEn = "Electricity" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "نجارة", NameEn = "Carpenter " },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "نقاشة", NameEn = "Painter" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "مكافحة الحشرات والطيور", NameEn = "Pest and bird control" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "ساتلايت ورسيفر", NameEn = "Satellite and receiver" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "التكييف", NameEn = "Air conditioning" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "تركيب و صيانة الاجهزة المنزلية", NameEn = "Installation and maintenance of home appliances" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "تنظيف حمام السباحة", NameEn = "Swimming pool cleaning" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "تسقيف", NameEn = "Roofing" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات سيارات الأجرة", NameEn = "Taxi services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات حكومية", NameEn = "Government services" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "المكتبات", NameEn = "Libraries" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "حدائق و منتجعات ترفيهيه", NameEn = "Parks and recreation" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "ترفيه", NameEn = "Entertainment" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "ضيافة", NameEn = "Hospitality" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "العقارات", NameEn = "Real estate" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "الرياضة", NameEn = "Sports" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "البناء", NameEn = "Construction" },
				new ServiceCategory { ID = Guid.NewGuid(), NameAr = "خدمات أخرى", NameEn = "Other services" }
			);
		}
	}
}
